// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/mlsolid/v1/mlsolid.proto

package mlservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MlsolidService_Experiments_FullMethodName         = "/mlsolid.v1.MlsolidService/Experiments"
	MlsolidService_Experiment_FullMethodName          = "/mlsolid.v1.MlsolidService/Experiment"
	MlsolidService_CreateRun_FullMethodName           = "/mlsolid.v1.MlsolidService/CreateRun"
	MlsolidService_Run_FullMethodName                 = "/mlsolid.v1.MlsolidService/Run"
	MlsolidService_Runs_FullMethodName                = "/mlsolid.v1.MlsolidService/Runs"
	MlsolidService_AddMetrics_FullMethodName          = "/mlsolid.v1.MlsolidService/AddMetrics"
	MlsolidService_AddArtifact_FullMethodName         = "/mlsolid.v1.MlsolidService/AddArtifact"
	MlsolidService_Artifact_FullMethodName            = "/mlsolid.v1.MlsolidService/Artifact"
	MlsolidService_CreateModelRegistry_FullMethodName = "/mlsolid.v1.MlsolidService/CreateModelRegistry"
	MlsolidService_ModelRegistry_FullMethodName       = "/mlsolid.v1.MlsolidService/ModelRegistry"
	MlsolidService_AddModelEntry_FullMethodName       = "/mlsolid.v1.MlsolidService/AddModelEntry"
	MlsolidService_TaggedModel_FullMethodName         = "/mlsolid.v1.MlsolidService/TaggedModel"
	MlsolidService_StreamTaggedModel_FullMethodName   = "/mlsolid.v1.MlsolidService/StreamTaggedModel"
	MlsolidService_TagModel_FullMethodName            = "/mlsolid.v1.MlsolidService/TagModel"
)

// MlsolidServiceClient is the client API for MlsolidService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MlsolidServiceClient interface {
	Experiments(ctx context.Context, in *ExperimentsRequest, opts ...grpc.CallOption) (*ExperimentsResponse, error)
	Experiment(ctx context.Context, in *ExperimentRequest, opts ...grpc.CallOption) (*ExperimentResponse, error)
	CreateRun(ctx context.Context, in *CreateRunRequest, opts ...grpc.CallOption) (*CreateRunResponse, error)
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	Runs(ctx context.Context, in *RunsRequest, opts ...grpc.CallOption) (*RunsResponse, error)
	AddMetrics(ctx context.Context, in *AddMetricsRequest, opts ...grpc.CallOption) (*AddMetricsResponse, error)
	AddArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AddArtifactRequest, AddArtifactResponse], error)
	Artifact(ctx context.Context, in *ArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArtifactResponse], error)
	// Model registry methods
	CreateModelRegistry(ctx context.Context, in *CreateModelRegistryRequest, opts ...grpc.CallOption) (*CreateModelRegistryResponse, error)
	ModelRegistry(ctx context.Context, in *ModelRegistryRequest, opts ...grpc.CallOption) (*ModelRegistryResponse, error)
	AddModelEntry(ctx context.Context, in *AddModelEntryRequest, opts ...grpc.CallOption) (*AddModelEntryResponse, error)
	TaggedModel(ctx context.Context, in *TaggedModelRequest, opts ...grpc.CallOption) (*TaggedModelResponse, error)
	StreamTaggedModel(ctx context.Context, in *StreamTaggedModelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamTaggedModelResponse], error)
	TagModel(ctx context.Context, in *TagModelRequest, opts ...grpc.CallOption) (*TagModelResponse, error)
}

type mlsolidServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMlsolidServiceClient(cc grpc.ClientConnInterface) MlsolidServiceClient {
	return &mlsolidServiceClient{cc}
}

func (c *mlsolidServiceClient) Experiments(ctx context.Context, in *ExperimentsRequest, opts ...grpc.CallOption) (*ExperimentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExperimentsResponse)
	err := c.cc.Invoke(ctx, MlsolidService_Experiments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsolidServiceClient) Experiment(ctx context.Context, in *ExperimentRequest, opts ...grpc.CallOption) (*ExperimentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExperimentResponse)
	err := c.cc.Invoke(ctx, MlsolidService_Experiment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsolidServiceClient) CreateRun(ctx context.Context, in *CreateRunRequest, opts ...grpc.CallOption) (*CreateRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRunResponse)
	err := c.cc.Invoke(ctx, MlsolidService_CreateRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsolidServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, MlsolidService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsolidServiceClient) Runs(ctx context.Context, in *RunsRequest, opts ...grpc.CallOption) (*RunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunsResponse)
	err := c.cc.Invoke(ctx, MlsolidService_Runs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsolidServiceClient) AddMetrics(ctx context.Context, in *AddMetricsRequest, opts ...grpc.CallOption) (*AddMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMetricsResponse)
	err := c.cc.Invoke(ctx, MlsolidService_AddMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsolidServiceClient) AddArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AddArtifactRequest, AddArtifactResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MlsolidService_ServiceDesc.Streams[0], MlsolidService_AddArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AddArtifactRequest, AddArtifactResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MlsolidService_AddArtifactClient = grpc.ClientStreamingClient[AddArtifactRequest, AddArtifactResponse]

func (c *mlsolidServiceClient) Artifact(ctx context.Context, in *ArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArtifactResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MlsolidService_ServiceDesc.Streams[1], MlsolidService_Artifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ArtifactRequest, ArtifactResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MlsolidService_ArtifactClient = grpc.ServerStreamingClient[ArtifactResponse]

func (c *mlsolidServiceClient) CreateModelRegistry(ctx context.Context, in *CreateModelRegistryRequest, opts ...grpc.CallOption) (*CreateModelRegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateModelRegistryResponse)
	err := c.cc.Invoke(ctx, MlsolidService_CreateModelRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsolidServiceClient) ModelRegistry(ctx context.Context, in *ModelRegistryRequest, opts ...grpc.CallOption) (*ModelRegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelRegistryResponse)
	err := c.cc.Invoke(ctx, MlsolidService_ModelRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsolidServiceClient) AddModelEntry(ctx context.Context, in *AddModelEntryRequest, opts ...grpc.CallOption) (*AddModelEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddModelEntryResponse)
	err := c.cc.Invoke(ctx, MlsolidService_AddModelEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsolidServiceClient) TaggedModel(ctx context.Context, in *TaggedModelRequest, opts ...grpc.CallOption) (*TaggedModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaggedModelResponse)
	err := c.cc.Invoke(ctx, MlsolidService_TaggedModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsolidServiceClient) StreamTaggedModel(ctx context.Context, in *StreamTaggedModelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamTaggedModelResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MlsolidService_ServiceDesc.Streams[2], MlsolidService_StreamTaggedModel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTaggedModelRequest, StreamTaggedModelResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MlsolidService_StreamTaggedModelClient = grpc.ServerStreamingClient[StreamTaggedModelResponse]

func (c *mlsolidServiceClient) TagModel(ctx context.Context, in *TagModelRequest, opts ...grpc.CallOption) (*TagModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagModelResponse)
	err := c.cc.Invoke(ctx, MlsolidService_TagModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MlsolidServiceServer is the server API for MlsolidService service.
// All implementations must embed UnimplementedMlsolidServiceServer
// for forward compatibility.
type MlsolidServiceServer interface {
	Experiments(context.Context, *ExperimentsRequest) (*ExperimentsResponse, error)
	Experiment(context.Context, *ExperimentRequest) (*ExperimentResponse, error)
	CreateRun(context.Context, *CreateRunRequest) (*CreateRunResponse, error)
	Run(context.Context, *RunRequest) (*RunResponse, error)
	Runs(context.Context, *RunsRequest) (*RunsResponse, error)
	AddMetrics(context.Context, *AddMetricsRequest) (*AddMetricsResponse, error)
	AddArtifact(grpc.ClientStreamingServer[AddArtifactRequest, AddArtifactResponse]) error
	Artifact(*ArtifactRequest, grpc.ServerStreamingServer[ArtifactResponse]) error
	// Model registry methods
	CreateModelRegistry(context.Context, *CreateModelRegistryRequest) (*CreateModelRegistryResponse, error)
	ModelRegistry(context.Context, *ModelRegistryRequest) (*ModelRegistryResponse, error)
	AddModelEntry(context.Context, *AddModelEntryRequest) (*AddModelEntryResponse, error)
	TaggedModel(context.Context, *TaggedModelRequest) (*TaggedModelResponse, error)
	StreamTaggedModel(*StreamTaggedModelRequest, grpc.ServerStreamingServer[StreamTaggedModelResponse]) error
	TagModel(context.Context, *TagModelRequest) (*TagModelResponse, error)
	mustEmbedUnimplementedMlsolidServiceServer()
}

// UnimplementedMlsolidServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMlsolidServiceServer struct{}

func (UnimplementedMlsolidServiceServer) Experiments(context.Context, *ExperimentsRequest) (*ExperimentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Experiments not implemented")
}
func (UnimplementedMlsolidServiceServer) Experiment(context.Context, *ExperimentRequest) (*ExperimentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Experiment not implemented")
}
func (UnimplementedMlsolidServiceServer) CreateRun(context.Context, *CreateRunRequest) (*CreateRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRun not implemented")
}
func (UnimplementedMlsolidServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedMlsolidServiceServer) Runs(context.Context, *RunsRequest) (*RunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Runs not implemented")
}
func (UnimplementedMlsolidServiceServer) AddMetrics(context.Context, *AddMetricsRequest) (*AddMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMetrics not implemented")
}
func (UnimplementedMlsolidServiceServer) AddArtifact(grpc.ClientStreamingServer[AddArtifactRequest, AddArtifactResponse]) error {
	return status.Error(codes.Unimplemented, "method AddArtifact not implemented")
}
func (UnimplementedMlsolidServiceServer) Artifact(*ArtifactRequest, grpc.ServerStreamingServer[ArtifactResponse]) error {
	return status.Error(codes.Unimplemented, "method Artifact not implemented")
}
func (UnimplementedMlsolidServiceServer) CreateModelRegistry(context.Context, *CreateModelRegistryRequest) (*CreateModelRegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateModelRegistry not implemented")
}
func (UnimplementedMlsolidServiceServer) ModelRegistry(context.Context, *ModelRegistryRequest) (*ModelRegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModelRegistry not implemented")
}
func (UnimplementedMlsolidServiceServer) AddModelEntry(context.Context, *AddModelEntryRequest) (*AddModelEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddModelEntry not implemented")
}
func (UnimplementedMlsolidServiceServer) TaggedModel(context.Context, *TaggedModelRequest) (*TaggedModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaggedModel not implemented")
}
func (UnimplementedMlsolidServiceServer) StreamTaggedModel(*StreamTaggedModelRequest, grpc.ServerStreamingServer[StreamTaggedModelResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamTaggedModel not implemented")
}
func (UnimplementedMlsolidServiceServer) TagModel(context.Context, *TagModelRequest) (*TagModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TagModel not implemented")
}
func (UnimplementedMlsolidServiceServer) mustEmbedUnimplementedMlsolidServiceServer() {}
func (UnimplementedMlsolidServiceServer) testEmbeddedByValue()                        {}

// UnsafeMlsolidServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MlsolidServiceServer will
// result in compilation errors.
type UnsafeMlsolidServiceServer interface {
	mustEmbedUnimplementedMlsolidServiceServer()
}

func RegisterMlsolidServiceServer(s grpc.ServiceRegistrar, srv MlsolidServiceServer) {
	// If the following call panics, it indicates UnimplementedMlsolidServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MlsolidService_ServiceDesc, srv)
}

func _MlsolidService_Experiments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExperimentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsolidServiceServer).Experiments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsolidService_Experiments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsolidServiceServer).Experiments(ctx, req.(*ExperimentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsolidService_Experiment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExperimentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsolidServiceServer).Experiment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsolidService_Experiment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsolidServiceServer).Experiment(ctx, req.(*ExperimentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsolidService_CreateRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsolidServiceServer).CreateRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsolidService_CreateRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsolidServiceServer).CreateRun(ctx, req.(*CreateRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsolidService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsolidServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsolidService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsolidServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsolidService_Runs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsolidServiceServer).Runs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsolidService_Runs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsolidServiceServer).Runs(ctx, req.(*RunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsolidService_AddMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsolidServiceServer).AddMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsolidService_AddMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsolidServiceServer).AddMetrics(ctx, req.(*AddMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsolidService_AddArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MlsolidServiceServer).AddArtifact(&grpc.GenericServerStream[AddArtifactRequest, AddArtifactResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MlsolidService_AddArtifactServer = grpc.ClientStreamingServer[AddArtifactRequest, AddArtifactResponse]

func _MlsolidService_Artifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ArtifactRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MlsolidServiceServer).Artifact(m, &grpc.GenericServerStream[ArtifactRequest, ArtifactResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MlsolidService_ArtifactServer = grpc.ServerStreamingServer[ArtifactResponse]

func _MlsolidService_CreateModelRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsolidServiceServer).CreateModelRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsolidService_CreateModelRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsolidServiceServer).CreateModelRegistry(ctx, req.(*CreateModelRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsolidService_ModelRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsolidServiceServer).ModelRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsolidService_ModelRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsolidServiceServer).ModelRegistry(ctx, req.(*ModelRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsolidService_AddModelEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddModelEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsolidServiceServer).AddModelEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsolidService_AddModelEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsolidServiceServer).AddModelEntry(ctx, req.(*AddModelEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsolidService_TaggedModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaggedModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsolidServiceServer).TaggedModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsolidService_TaggedModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsolidServiceServer).TaggedModel(ctx, req.(*TaggedModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsolidService_StreamTaggedModel_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTaggedModelRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MlsolidServiceServer).StreamTaggedModel(m, &grpc.GenericServerStream[StreamTaggedModelRequest, StreamTaggedModelResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MlsolidService_StreamTaggedModelServer = grpc.ServerStreamingServer[StreamTaggedModelResponse]

func _MlsolidService_TagModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsolidServiceServer).TagModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsolidService_TagModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsolidServiceServer).TagModel(ctx, req.(*TagModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MlsolidService_ServiceDesc is the grpc.ServiceDesc for MlsolidService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MlsolidService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mlsolid.v1.MlsolidService",
	HandlerType: (*MlsolidServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Experiments",
			Handler:    _MlsolidService_Experiments_Handler,
		},
		{
			MethodName: "Experiment",
			Handler:    _MlsolidService_Experiment_Handler,
		},
		{
			MethodName: "CreateRun",
			Handler:    _MlsolidService_CreateRun_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _MlsolidService_Run_Handler,
		},
		{
			MethodName: "Runs",
			Handler:    _MlsolidService_Runs_Handler,
		},
		{
			MethodName: "AddMetrics",
			Handler:    _MlsolidService_AddMetrics_Handler,
		},
		{
			MethodName: "CreateModelRegistry",
			Handler:    _MlsolidService_CreateModelRegistry_Handler,
		},
		{
			MethodName: "ModelRegistry",
			Handler:    _MlsolidService_ModelRegistry_Handler,
		},
		{
			MethodName: "AddModelEntry",
			Handler:    _MlsolidService_AddModelEntry_Handler,
		},
		{
			MethodName: "TaggedModel",
			Handler:    _MlsolidService_TaggedModel_Handler,
		},
		{
			MethodName: "TagModel",
			Handler:    _MlsolidService_TagModel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddArtifact",
			Handler:       _MlsolidService_AddArtifact_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Artifact",
			Handler:       _MlsolidService_Artifact_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamTaggedModel",
			Handler:       _MlsolidService_StreamTaggedModel_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mlsolid/v1/mlsolid.proto",
}
