// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/mlsolid/v1/mlsolid.proto

package mlservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_PENDING     Status = 1
	Status_STATUS_PROGRESS    Status = 2
	Status_STATUS_SUCCESS     Status = 3
	Status_STATUS_FAILED      Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_PROGRESS",
		3: "STATUS_SUCCESS",
		4: "STATUS_FAILED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_PROGRESS":    2,
		"STATUS_SUCCESS":     3,
		"STATUS_FAILED":      4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mlsolid_v1_mlsolid_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_mlsolid_v1_mlsolid_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{0}
}

type Val struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Val:
	//
	//	*Val_Int
	//	*Val_Double
	//	*Val_Str
	Val           isVal_Val `protobuf_oneof:"val"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Val) Reset() {
	*x = Val{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Val) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Val) ProtoMessage() {}

func (x *Val) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Val.ProtoReflect.Descriptor instead.
func (*Val) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{0}
}

func (x *Val) GetVal() isVal_Val {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *Val) GetInt() int64 {
	if x != nil {
		if x, ok := x.Val.(*Val_Int); ok {
			return x.Int
		}
	}
	return 0
}

func (x *Val) GetDouble() float64 {
	if x != nil {
		if x, ok := x.Val.(*Val_Double); ok {
			return x.Double
		}
	}
	return 0
}

func (x *Val) GetStr() string {
	if x != nil {
		if x, ok := x.Val.(*Val_Str); ok {
			return x.Str
		}
	}
	return ""
}

type isVal_Val interface {
	isVal_Val()
}

type Val_Int struct {
	Int int64 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type Val_Double struct {
	Double float64 `protobuf:"fixed64,3,opt,name=double,proto3,oneof"`
}

type Val_Str struct {
	Str string `protobuf:"bytes,4,opt,name=str,proto3,oneof"`
}

func (*Val_Int) isVal_Val() {}

func (*Val_Double) isVal_Val() {}

func (*Val_Str) isVal_Val() {}

type MetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{1}
}

func (x *MetaData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetaData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetaData) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{2}
}

func (x *Content) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vals          []*Val                 `protobuf:"bytes,2,rep,name=vals,proto3" json:"vals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{3}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetVals() []*Val {
	if x != nil {
		return x.Vals
	}
	return nil
}

type Run struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExperimentId  string                 `protobuf:"bytes,3,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	Metrics       map[string]*Metric     `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{4}
}

func (x *Run) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Run) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Run) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *Run) GetMetrics() map[string]*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ModelEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelEntry) Reset() {
	*x = ModelEntry{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelEntry) ProtoMessage() {}

func (x *ModelEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelEntry.ProtoReflect.Descriptor instead.
func (*ModelEntry) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{5}
}

func (x *ModelEntry) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ModelEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ModelEntryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indx          []int32                `protobuf:"varint,1,rep,packed,name=indx,proto3" json:"indx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelEntryList) Reset() {
	*x = ModelEntryList{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelEntryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelEntryList) ProtoMessage() {}

func (x *ModelEntryList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelEntryList.ProtoReflect.Descriptor instead.
func (*ModelEntryList) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{6}
}

func (x *ModelEntryList) GetIndx() []int32 {
	if x != nil {
		return x.Indx
	}
	return nil
}

type ModelEntryTags struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Entries       map[string]*ModelEntryList `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelEntryTags) Reset() {
	*x = ModelEntryTags{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelEntryTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelEntryTags) ProtoMessage() {}

func (x *ModelEntryTags) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelEntryTags.ProtoReflect.Descriptor instead.
func (*ModelEntryTags) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{7}
}

func (x *ModelEntryTags) GetEntries() map[string]*ModelEntryList {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ExperimentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentsRequest) Reset() {
	*x = ExperimentsRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentsRequest) ProtoMessage() {}

func (x *ExperimentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentsRequest.ProtoReflect.Descriptor instead.
func (*ExperimentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{8}
}

type ExperimentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpIds        []string               `protobuf:"bytes,1,rep,name=exp_ids,json=expIds,proto3" json:"exp_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentsResponse) Reset() {
	*x = ExperimentsResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentsResponse) ProtoMessage() {}

func (x *ExperimentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentsResponse.ProtoReflect.Descriptor instead.
func (*ExperimentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{9}
}

func (x *ExperimentsResponse) GetExpIds() []string {
	if x != nil {
		return x.ExpIds
	}
	return nil
}

type ExperimentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpId         string                 `protobuf:"bytes,1,opt,name=exp_id,json=expId,proto3" json:"exp_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentRequest) Reset() {
	*x = ExperimentRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentRequest) ProtoMessage() {}

func (x *ExperimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentRequest.ProtoReflect.Descriptor instead.
func (*ExperimentRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{10}
}

func (x *ExperimentRequest) GetExpId() string {
	if x != nil {
		return x.ExpId
	}
	return ""
}

type ExperimentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunIds        []string               `protobuf:"bytes,1,rep,name=run_ids,json=runIds,proto3" json:"run_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentResponse) Reset() {
	*x = ExperimentResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentResponse) ProtoMessage() {}

func (x *ExperimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentResponse.ProtoReflect.Descriptor instead.
func (*ExperimentResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{11}
}

func (x *ExperimentResponse) GetRunIds() []string {
	if x != nil {
		return x.RunIds
	}
	return nil
}

type CreateRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ExperimentId  string                 `protobuf:"bytes,2,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRunRequest) Reset() {
	*x = CreateRunRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunRequest) ProtoMessage() {}

func (x *CreateRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunRequest.ProtoReflect.Descriptor instead.
func (*CreateRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{12}
}

func (x *CreateRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CreateRunRequest) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

type CreateRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRunResponse) Reset() {
	*x = CreateRunResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunResponse) ProtoMessage() {}

func (x *CreateRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunResponse.ProtoReflect.Descriptor instead.
func (*CreateRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRunResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{14}
}

func (x *RunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExperimentId  string                 `protobuf:"bytes,3,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	Metrics       map[string]*Metric     `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{15}
}

func (x *RunResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RunResponse) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *RunResponse) GetMetrics() map[string]*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type RunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunIds        []string               `protobuf:"bytes,1,rep,name=run_ids,json=runIds,proto3" json:"run_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunsRequest) Reset() {
	*x = RunsRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunsRequest) ProtoMessage() {}

func (x *RunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunsRequest.ProtoReflect.Descriptor instead.
func (*RunsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{16}
}

func (x *RunsRequest) GetRunIds() []string {
	if x != nil {
		return x.RunIds
	}
	return nil
}

type RunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*Run                 `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunsResponse) Reset() {
	*x = RunsResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunsResponse) ProtoMessage() {}

func (x *RunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunsResponse.ProtoReflect.Descriptor instead.
func (*RunsResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{17}
}

func (x *RunsResponse) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

type AddMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMetricsRequest) Reset() {
	*x = AddMetricsRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMetricsRequest) ProtoMessage() {}

func (x *AddMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMetricsRequest.ProtoReflect.Descriptor instead.
func (*AddMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{18}
}

func (x *AddMetricsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AddMetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type AddMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         bool                   `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMetricsResponse) Reset() {
	*x = AddMetricsResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMetricsResponse) ProtoMessage() {}

func (x *AddMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMetricsResponse.ProtoReflect.Descriptor instead.
func (*AddMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{19}
}

func (x *AddMetricsResponse) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

type AddArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*AddArtifactRequest_Metadata
	//	*AddArtifactRequest_Content
	Request       isAddArtifactRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArtifactRequest) Reset() {
	*x = AddArtifactRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArtifactRequest) ProtoMessage() {}

func (x *AddArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArtifactRequest.ProtoReflect.Descriptor instead.
func (*AddArtifactRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{20}
}

func (x *AddArtifactRequest) GetRequest() isAddArtifactRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AddArtifactRequest) GetMetadata() *MetaData {
	if x != nil {
		if x, ok := x.Request.(*AddArtifactRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *AddArtifactRequest) GetContent() *Content {
	if x != nil {
		if x, ok := x.Request.(*AddArtifactRequest_Content); ok {
			return x.Content
		}
	}
	return nil
}

type isAddArtifactRequest_Request interface {
	isAddArtifactRequest_Request()
}

type AddArtifactRequest_Metadata struct {
	Metadata *MetaData `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type AddArtifactRequest_Content struct {
	Content *Content `protobuf:"bytes,2,opt,name=content,proto3,oneof"`
}

func (*AddArtifactRequest_Metadata) isAddArtifactRequest_Request() {}

func (*AddArtifactRequest_Content) isAddArtifactRequest_Request() {}

type AddArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=mlsolid.v1.Status" json:"status,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	S3Url         string                 `protobuf:"bytes,4,opt,name=s3_url,json=s3Url,proto3" json:"s3_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArtifactResponse) Reset() {
	*x = AddArtifactResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArtifactResponse) ProtoMessage() {}

func (x *AddArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArtifactResponse.ProtoReflect.Descriptor instead.
func (*AddArtifactResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{21}
}

func (x *AddArtifactResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddArtifactResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *AddArtifactResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AddArtifactResponse) GetS3Url() string {
	if x != nil {
		return x.S3Url
	}
	return ""
}

type ArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ArtifactName  string                 `protobuf:"bytes,2,opt,name=artifact_name,json=artifactName,proto3" json:"artifact_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRequest) Reset() {
	*x = ArtifactRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRequest) ProtoMessage() {}

func (x *ArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRequest.ProtoReflect.Descriptor instead.
func (*ArtifactRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{22}
}

func (x *ArtifactRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ArtifactRequest) GetArtifactName() string {
	if x != nil {
		return x.ArtifactName
	}
	return ""
}

type ArtifactResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ArtifactResponse_Metadata
	//	*ArtifactResponse_Content
	Request       isArtifactResponse_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactResponse) Reset() {
	*x = ArtifactResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactResponse) ProtoMessage() {}

func (x *ArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactResponse.ProtoReflect.Descriptor instead.
func (*ArtifactResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{23}
}

func (x *ArtifactResponse) GetRequest() isArtifactResponse_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ArtifactResponse) GetMetadata() *MetaData {
	if x != nil {
		if x, ok := x.Request.(*ArtifactResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *ArtifactResponse) GetContent() *Content {
	if x != nil {
		if x, ok := x.Request.(*ArtifactResponse_Content); ok {
			return x.Content
		}
	}
	return nil
}

type isArtifactResponse_Request interface {
	isArtifactResponse_Request()
}

type ArtifactResponse_Metadata struct {
	Metadata *MetaData `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type ArtifactResponse_Content struct {
	Content *Content `protobuf:"bytes,2,opt,name=content,proto3,oneof"`
}

func (*ArtifactResponse_Metadata) isArtifactResponse_Request() {}

func (*ArtifactResponse_Content) isArtifactResponse_Request() {}

type CreateModelRegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelRegistryRequest) Reset() {
	*x = CreateModelRegistryRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRegistryRequest) ProtoMessage() {}

func (x *CreateModelRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRegistryRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRegistryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{24}
}

func (x *CreateModelRegistryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateModelRegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelRegistryResponse) Reset() {
	*x = CreateModelRegistryResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRegistryResponse) ProtoMessage() {}

func (x *CreateModelRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRegistryResponse.ProtoReflect.Descriptor instead.
func (*CreateModelRegistryResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{25}
}

func (x *CreateModelRegistryResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type ModelRegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelRegistryRequest) Reset() {
	*x = ModelRegistryRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRegistryRequest) ProtoMessage() {}

func (x *ModelRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRegistryRequest.ProtoReflect.Descriptor instead.
func (*ModelRegistryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{26}
}

func (x *ModelRegistryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ModelRegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ModelEntries  []*ModelEntry          `protobuf:"bytes,2,rep,name=model_entries,json=modelEntries,proto3" json:"model_entries,omitempty"`
	Tags          *ModelEntryTags        `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelRegistryResponse) Reset() {
	*x = ModelRegistryResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRegistryResponse) ProtoMessage() {}

func (x *ModelRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRegistryResponse.ProtoReflect.Descriptor instead.
func (*ModelRegistryResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{27}
}

func (x *ModelRegistryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelRegistryResponse) GetModelEntries() []*ModelEntry {
	if x != nil {
		return x.ModelEntries
	}
	return nil
}

func (x *ModelRegistryResponse) GetTags() *ModelEntryTags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AddModelEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,3,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddModelEntryRequest) Reset() {
	*x = AddModelEntryRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddModelEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddModelEntryRequest) ProtoMessage() {}

func (x *AddModelEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddModelEntryRequest.ProtoReflect.Descriptor instead.
func (*AddModelEntryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{28}
}

func (x *AddModelEntryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddModelEntryRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AddModelEntryRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *AddModelEntryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AddModelEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         bool                   `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddModelEntryResponse) Reset() {
	*x = AddModelEntryResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddModelEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddModelEntryResponse) ProtoMessage() {}

func (x *AddModelEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddModelEntryResponse.ProtoReflect.Descriptor instead.
func (*AddModelEntryResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{29}
}

func (x *AddModelEntryResponse) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

type TaggedModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaggedModelRequest) Reset() {
	*x = TaggedModelRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaggedModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaggedModelRequest) ProtoMessage() {}

func (x *TaggedModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaggedModelRequest.ProtoReflect.Descriptor instead.
func (*TaggedModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{30}
}

func (x *TaggedModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaggedModelRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type TaggedModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *ModelEntry            `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaggedModelResponse) Reset() {
	*x = TaggedModelResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaggedModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaggedModelResponse) ProtoMessage() {}

func (x *TaggedModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaggedModelResponse.ProtoReflect.Descriptor instead.
func (*TaggedModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{31}
}

func (x *TaggedModelResponse) GetEntry() *ModelEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type StreamTaggedModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTaggedModelRequest) Reset() {
	*x = StreamTaggedModelRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTaggedModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTaggedModelRequest) ProtoMessage() {}

func (x *StreamTaggedModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTaggedModelRequest.ProtoReflect.Descriptor instead.
func (*StreamTaggedModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{32}
}

func (x *StreamTaggedModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamTaggedModelRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type StreamTaggedModelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*StreamTaggedModelResponse_Metadata
	//	*StreamTaggedModelResponse_Content
	Response      isStreamTaggedModelResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTaggedModelResponse) Reset() {
	*x = StreamTaggedModelResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTaggedModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTaggedModelResponse) ProtoMessage() {}

func (x *StreamTaggedModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTaggedModelResponse.ProtoReflect.Descriptor instead.
func (*StreamTaggedModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{33}
}

func (x *StreamTaggedModelResponse) GetResponse() isStreamTaggedModelResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *StreamTaggedModelResponse) GetMetadata() *MetaData {
	if x != nil {
		if x, ok := x.Response.(*StreamTaggedModelResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *StreamTaggedModelResponse) GetContent() *Content {
	if x != nil {
		if x, ok := x.Response.(*StreamTaggedModelResponse_Content); ok {
			return x.Content
		}
	}
	return nil
}

type isStreamTaggedModelResponse_Response interface {
	isStreamTaggedModelResponse_Response()
}

type StreamTaggedModelResponse_Metadata struct {
	Metadata *MetaData `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type StreamTaggedModelResponse_Content struct {
	Content *Content `protobuf:"bytes,2,opt,name=content,proto3,oneof"`
}

func (*StreamTaggedModelResponse_Metadata) isStreamTaggedModelResponse_Response() {}

func (*StreamTaggedModelResponse_Content) isStreamTaggedModelResponse_Response() {}

type TagModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagModelRequest) Reset() {
	*x = TagModelRequest{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagModelRequest) ProtoMessage() {}

func (x *TagModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagModelRequest.ProtoReflect.Descriptor instead.
func (*TagModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{34}
}

func (x *TagModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagModelRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TagModelRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TagModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         bool                   `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagModelResponse) Reset() {
	*x = TagModelResponse{}
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagModelResponse) ProtoMessage() {}

func (x *TagModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mlsolid_v1_mlsolid_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagModelResponse.ProtoReflect.Descriptor instead.
func (*TagModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP(), []int{35}
}

func (x *TagModelResponse) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

var File_proto_mlsolid_v1_mlsolid_proto protoreflect.FileDescriptor

const file_proto_mlsolid_v1_mlsolid_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/mlsolid/v1/mlsolid.proto\x12\n" +
	"mlsolid.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"N\n" +
	"\x03Val\x12\x12\n" +
	"\x03int\x18\x02 \x01(\x03H\x00R\x03int\x12\x18\n" +
	"\x06double\x18\x03 \x01(\x01H\x00R\x06double\x12\x12\n" +
	"\x03str\x18\x04 \x01(\tH\x00R\x03strB\x05\n" +
	"\x03val\"I\n" +
	"\bMetaData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"#\n" +
	"\aContent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"A\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\x04vals\x18\x02 \x03(\v2\x0f.mlsolid.v1.ValR\x04vals\"\x83\x02\n" +
	"\x03Run\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\rexperiment_id\x18\x03 \x01(\tR\fexperimentId\x126\n" +
	"\ametrics\x18\x04 \x03(\v2\x1c.mlsolid.v1.Run.MetricsEntryR\ametrics\x1aN\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.mlsolid.v1.MetricR\x05value:\x028\x01\"2\n" +
	"\n" +
	"ModelEntry\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"$\n" +
	"\x0eModelEntryList\x12\x12\n" +
	"\x04indx\x18\x01 \x03(\x05R\x04indx\"\xab\x01\n" +
	"\x0eModelEntryTags\x12A\n" +
	"\aentries\x18\x01 \x03(\v2'.mlsolid.v1.ModelEntryTags.EntriesEntryR\aentries\x1aV\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.mlsolid.v1.ModelEntryListR\x05value:\x028\x01\"\x14\n" +
	"\x12ExperimentsRequest\".\n" +
	"\x13ExperimentsResponse\x12\x17\n" +
	"\aexp_ids\x18\x01 \x03(\tR\x06expIds\"*\n" +
	"\x11ExperimentRequest\x12\x15\n" +
	"\x06exp_id\x18\x01 \x01(\tR\x05expId\"-\n" +
	"\x12ExperimentResponse\x12\x17\n" +
	"\arun_ids\x18\x01 \x03(\tR\x06runIds\"N\n" +
	"\x10CreateRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rexperiment_id\x18\x02 \x01(\tR\fexperimentId\"*\n" +
	"\x11CreateRunResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"#\n" +
	"\n" +
	"RunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x93\x02\n" +
	"\vRunResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\rexperiment_id\x18\x03 \x01(\tR\fexperimentId\x12>\n" +
	"\ametrics\x18\x04 \x03(\v2$.mlsolid.v1.RunResponse.MetricsEntryR\ametrics\x1aN\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.mlsolid.v1.MetricR\x05value:\x028\x01\"&\n" +
	"\vRunsRequest\x12\x17\n" +
	"\arun_ids\x18\x01 \x03(\tR\x06runIds\"3\n" +
	"\fRunsResponse\x12#\n" +
	"\x04runs\x18\x01 \x03(\v2\x0f.mlsolid.v1.RunR\x04runs\"X\n" +
	"\x11AddMetricsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12,\n" +
	"\ametrics\x18\x02 \x03(\v2\x12.mlsolid.v1.MetricR\ametrics\"*\n" +
	"\x12AddMetricsResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\bR\x05added\"\x84\x01\n" +
	"\x12AddArtifactRequest\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.mlsolid.v1.MetaDataH\x00R\bmetadata\x12/\n" +
	"\acontent\x18\x02 \x01(\v2\x13.mlsolid.v1.ContentH\x00R\acontentB\t\n" +
	"\arequest\"\x80\x01\n" +
	"\x13AddArtifactResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.mlsolid.v1.StatusR\x06status\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x15\n" +
	"\x06s3_url\x18\x04 \x01(\tR\x05s3Url\"M\n" +
	"\x0fArtifactRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rartifact_name\x18\x02 \x01(\tR\fartifactName\"\x82\x01\n" +
	"\x10ArtifactResponse\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.mlsolid.v1.MetaDataH\x00R\bmetadata\x12/\n" +
	"\acontent\x18\x02 \x01(\v2\x13.mlsolid.v1.ContentH\x00R\acontentB\t\n" +
	"\arequest\"0\n" +
	"\x1aCreateModelRegistryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x1bCreateModelRegistryResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\"*\n" +
	"\x14ModelRegistryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x98\x01\n" +
	"\x15ModelRegistryResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\rmodel_entries\x18\x02 \x03(\v2\x16.mlsolid.v1.ModelEntryR\fmodelEntries\x12.\n" +
	"\x04tags\x18\x03 \x01(\v2\x1a.mlsolid.v1.ModelEntryTagsR\x04tags\"v\n" +
	"\x14AddModelEntryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1f\n" +
	"\vartifact_id\x18\x03 \x01(\tR\n" +
	"artifactId\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"-\n" +
	"\x15AddModelEntryResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\bR\x05added\":\n" +
	"\x12TaggedModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\"C\n" +
	"\x13TaggedModelResponse\x12,\n" +
	"\x05entry\x18\x01 \x01(\v2\x16.mlsolid.v1.ModelEntryR\x05entry\"@\n" +
	"\x18StreamTaggedModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\"\x8c\x01\n" +
	"\x19StreamTaggedModelResponse\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.mlsolid.v1.MetaDataH\x00R\bmetadata\x12/\n" +
	"\acontent\x18\x02 \x01(\v2\x13.mlsolid.v1.ContentH\x00R\acontentB\n" +
	"\n" +
	"\bresponse\"S\n" +
	"\x0fTagModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"(\n" +
	"\x10TagModelResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\bR\x05added*p\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x13\n" +
	"\x0fSTATUS_PROGRESS\x10\x02\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x03\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x042\xe1\b\n" +
	"\x0eMlsolidService\x12N\n" +
	"\vExperiments\x12\x1e.mlsolid.v1.ExperimentsRequest\x1a\x1f.mlsolid.v1.ExperimentsResponse\x12K\n" +
	"\n" +
	"Experiment\x12\x1d.mlsolid.v1.ExperimentRequest\x1a\x1e.mlsolid.v1.ExperimentResponse\x12H\n" +
	"\tCreateRun\x12\x1c.mlsolid.v1.CreateRunRequest\x1a\x1d.mlsolid.v1.CreateRunResponse\x126\n" +
	"\x03Run\x12\x16.mlsolid.v1.RunRequest\x1a\x17.mlsolid.v1.RunResponse\x129\n" +
	"\x04Runs\x12\x17.mlsolid.v1.RunsRequest\x1a\x18.mlsolid.v1.RunsResponse\x12K\n" +
	"\n" +
	"AddMetrics\x12\x1d.mlsolid.v1.AddMetricsRequest\x1a\x1e.mlsolid.v1.AddMetricsResponse\x12P\n" +
	"\vAddArtifact\x12\x1e.mlsolid.v1.AddArtifactRequest\x1a\x1f.mlsolid.v1.AddArtifactResponse(\x01\x12G\n" +
	"\bArtifact\x12\x1b.mlsolid.v1.ArtifactRequest\x1a\x1c.mlsolid.v1.ArtifactResponse0\x01\x12f\n" +
	"\x13CreateModelRegistry\x12&.mlsolid.v1.CreateModelRegistryRequest\x1a'.mlsolid.v1.CreateModelRegistryResponse\x12T\n" +
	"\rModelRegistry\x12 .mlsolid.v1.ModelRegistryRequest\x1a!.mlsolid.v1.ModelRegistryResponse\x12T\n" +
	"\rAddModelEntry\x12 .mlsolid.v1.AddModelEntryRequest\x1a!.mlsolid.v1.AddModelEntryResponse\x12N\n" +
	"\vTaggedModel\x12\x1e.mlsolid.v1.TaggedModelRequest\x1a\x1f.mlsolid.v1.TaggedModelResponse\x12b\n" +
	"\x11StreamTaggedModel\x12$.mlsolid.v1.StreamTaggedModelRequest\x1a%.mlsolid.v1.StreamTaggedModelResponse0\x01\x12E\n" +
	"\bTagModel\x12\x1b.mlsolid.v1.TagModelRequest\x1a\x1c.mlsolid.v1.TagModelResponseB(Z&github.com/pvavrina/goml/api/mlserviceb\x06proto3"

var (
	file_proto_mlsolid_v1_mlsolid_proto_rawDescOnce sync.Once
	file_proto_mlsolid_v1_mlsolid_proto_rawDescData []byte
)

func file_proto_mlsolid_v1_mlsolid_proto_rawDescGZIP() []byte {
	file_proto_mlsolid_v1_mlsolid_proto_rawDescOnce.Do(func() {
		file_proto_mlsolid_v1_mlsolid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mlsolid_v1_mlsolid_proto_rawDesc), len(file_proto_mlsolid_v1_mlsolid_proto_rawDesc)))
	})
	return file_proto_mlsolid_v1_mlsolid_proto_rawDescData
}

var file_proto_mlsolid_v1_mlsolid_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_mlsolid_v1_mlsolid_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_proto_mlsolid_v1_mlsolid_proto_goTypes = []any{
	(Status)(0),                         // 0: mlsolid.v1.Status
	(*Val)(nil),                         // 1: mlsolid.v1.Val
	(*MetaData)(nil),                    // 2: mlsolid.v1.MetaData
	(*Content)(nil),                     // 3: mlsolid.v1.Content
	(*Metric)(nil),                      // 4: mlsolid.v1.Metric
	(*Run)(nil),                         // 5: mlsolid.v1.Run
	(*ModelEntry)(nil),                  // 6: mlsolid.v1.ModelEntry
	(*ModelEntryList)(nil),              // 7: mlsolid.v1.ModelEntryList
	(*ModelEntryTags)(nil),              // 8: mlsolid.v1.ModelEntryTags
	(*ExperimentsRequest)(nil),          // 9: mlsolid.v1.ExperimentsRequest
	(*ExperimentsResponse)(nil),         // 10: mlsolid.v1.ExperimentsResponse
	(*ExperimentRequest)(nil),           // 11: mlsolid.v1.ExperimentRequest
	(*ExperimentResponse)(nil),          // 12: mlsolid.v1.ExperimentResponse
	(*CreateRunRequest)(nil),            // 13: mlsolid.v1.CreateRunRequest
	(*CreateRunResponse)(nil),           // 14: mlsolid.v1.CreateRunResponse
	(*RunRequest)(nil),                  // 15: mlsolid.v1.RunRequest
	(*RunResponse)(nil),                 // 16: mlsolid.v1.RunResponse
	(*RunsRequest)(nil),                 // 17: mlsolid.v1.RunsRequest
	(*RunsResponse)(nil),                // 18: mlsolid.v1.RunsResponse
	(*AddMetricsRequest)(nil),           // 19: mlsolid.v1.AddMetricsRequest
	(*AddMetricsResponse)(nil),          // 20: mlsolid.v1.AddMetricsResponse
	(*AddArtifactRequest)(nil),          // 21: mlsolid.v1.AddArtifactRequest
	(*AddArtifactResponse)(nil),         // 22: mlsolid.v1.AddArtifactResponse
	(*ArtifactRequest)(nil),             // 23: mlsolid.v1.ArtifactRequest
	(*ArtifactResponse)(nil),            // 24: mlsolid.v1.ArtifactResponse
	(*CreateModelRegistryRequest)(nil),  // 25: mlsolid.v1.CreateModelRegistryRequest
	(*CreateModelRegistryResponse)(nil), // 26: mlsolid.v1.CreateModelRegistryResponse
	(*ModelRegistryRequest)(nil),        // 27: mlsolid.v1.ModelRegistryRequest
	(*ModelRegistryResponse)(nil),       // 28: mlsolid.v1.ModelRegistryResponse
	(*AddModelEntryRequest)(nil),        // 29: mlsolid.v1.AddModelEntryRequest
	(*AddModelEntryResponse)(nil),       // 30: mlsolid.v1.AddModelEntryResponse
	(*TaggedModelRequest)(nil),          // 31: mlsolid.v1.TaggedModelRequest
	(*TaggedModelResponse)(nil),         // 32: mlsolid.v1.TaggedModelResponse
	(*StreamTaggedModelRequest)(nil),    // 33: mlsolid.v1.StreamTaggedModelRequest
	(*StreamTaggedModelResponse)(nil),   // 34: mlsolid.v1.StreamTaggedModelResponse
	(*TagModelRequest)(nil),             // 35: mlsolid.v1.TagModelRequest
	(*TagModelResponse)(nil),            // 36: mlsolid.v1.TagModelResponse
	nil,                                 // 37: mlsolid.v1.Run.MetricsEntry
	nil,                                 // 38: mlsolid.v1.ModelEntryTags.EntriesEntry
	nil,                                 // 39: mlsolid.v1.RunResponse.MetricsEntry
	(*timestamppb.Timestamp)(nil),       // 40: google.protobuf.Timestamp
}
var file_proto_mlsolid_v1_mlsolid_proto_depIdxs = []int32{
	1,  // 0: mlsolid.v1.Metric.vals:type_name -> mlsolid.v1.Val
	40, // 1: mlsolid.v1.Run.timestamp:type_name -> google.protobuf.Timestamp
	37, // 2: mlsolid.v1.Run.metrics:type_name -> mlsolid.v1.Run.MetricsEntry
	38, // 3: mlsolid.v1.ModelEntryTags.entries:type_name -> mlsolid.v1.ModelEntryTags.EntriesEntry
	40, // 4: mlsolid.v1.RunResponse.timestamp:type_name -> google.protobuf.Timestamp
	39, // 5: mlsolid.v1.RunResponse.metrics:type_name -> mlsolid.v1.RunResponse.MetricsEntry
	5,  // 6: mlsolid.v1.RunsResponse.runs:type_name -> mlsolid.v1.Run
	4,  // 7: mlsolid.v1.AddMetricsRequest.metrics:type_name -> mlsolid.v1.Metric
	2,  // 8: mlsolid.v1.AddArtifactRequest.metadata:type_name -> mlsolid.v1.MetaData
	3,  // 9: mlsolid.v1.AddArtifactRequest.content:type_name -> mlsolid.v1.Content
	0,  // 10: mlsolid.v1.AddArtifactResponse.status:type_name -> mlsolid.v1.Status
	2,  // 11: mlsolid.v1.ArtifactResponse.metadata:type_name -> mlsolid.v1.MetaData
	3,  // 12: mlsolid.v1.ArtifactResponse.content:type_name -> mlsolid.v1.Content
	6,  // 13: mlsolid.v1.ModelRegistryResponse.model_entries:type_name -> mlsolid.v1.ModelEntry
	8,  // 14: mlsolid.v1.ModelRegistryResponse.tags:type_name -> mlsolid.v1.ModelEntryTags
	6,  // 15: mlsolid.v1.TaggedModelResponse.entry:type_name -> mlsolid.v1.ModelEntry
	2,  // 16: mlsolid.v1.StreamTaggedModelResponse.metadata:type_name -> mlsolid.v1.MetaData
	3,  // 17: mlsolid.v1.StreamTaggedModelResponse.content:type_name -> mlsolid.v1.Content
	4,  // 18: mlsolid.v1.Run.MetricsEntry.value:type_name -> mlsolid.v1.Metric
	7,  // 19: mlsolid.v1.ModelEntryTags.EntriesEntry.value:type_name -> mlsolid.v1.ModelEntryList
	4,  // 20: mlsolid.v1.RunResponse.MetricsEntry.value:type_name -> mlsolid.v1.Metric
	9,  // 21: mlsolid.v1.MlsolidService.Experiments:input_type -> mlsolid.v1.ExperimentsRequest
	11, // 22: mlsolid.v1.MlsolidService.Experiment:input_type -> mlsolid.v1.ExperimentRequest
	13, // 23: mlsolid.v1.MlsolidService.CreateRun:input_type -> mlsolid.v1.CreateRunRequest
	15, // 24: mlsolid.v1.MlsolidService.Run:input_type -> mlsolid.v1.RunRequest
	17, // 25: mlsolid.v1.MlsolidService.Runs:input_type -> mlsolid.v1.RunsRequest
	19, // 26: mlsolid.v1.MlsolidService.AddMetrics:input_type -> mlsolid.v1.AddMetricsRequest
	21, // 27: mlsolid.v1.MlsolidService.AddArtifact:input_type -> mlsolid.v1.AddArtifactRequest
	23, // 28: mlsolid.v1.MlsolidService.Artifact:input_type -> mlsolid.v1.ArtifactRequest
	25, // 29: mlsolid.v1.MlsolidService.CreateModelRegistry:input_type -> mlsolid.v1.CreateModelRegistryRequest
	27, // 30: mlsolid.v1.MlsolidService.ModelRegistry:input_type -> mlsolid.v1.ModelRegistryRequest
	29, // 31: mlsolid.v1.MlsolidService.AddModelEntry:input_type -> mlsolid.v1.AddModelEntryRequest
	31, // 32: mlsolid.v1.MlsolidService.TaggedModel:input_type -> mlsolid.v1.TaggedModelRequest
	33, // 33: mlsolid.v1.MlsolidService.StreamTaggedModel:input_type -> mlsolid.v1.StreamTaggedModelRequest
	35, // 34: mlsolid.v1.MlsolidService.TagModel:input_type -> mlsolid.v1.TagModelRequest
	10, // 35: mlsolid.v1.MlsolidService.Experiments:output_type -> mlsolid.v1.ExperimentsResponse
	12, // 36: mlsolid.v1.MlsolidService.Experiment:output_type -> mlsolid.v1.ExperimentResponse
	14, // 37: mlsolid.v1.MlsolidService.CreateRun:output_type -> mlsolid.v1.CreateRunResponse
	16, // 38: mlsolid.v1.MlsolidService.Run:output_type -> mlsolid.v1.RunResponse
	18, // 39: mlsolid.v1.MlsolidService.Runs:output_type -> mlsolid.v1.RunsResponse
	20, // 40: mlsolid.v1.MlsolidService.AddMetrics:output_type -> mlsolid.v1.AddMetricsResponse
	22, // 41: mlsolid.v1.MlsolidService.AddArtifact:output_type -> mlsolid.v1.AddArtifactResponse
	24, // 42: mlsolid.v1.MlsolidService.Artifact:output_type -> mlsolid.v1.ArtifactResponse
	26, // 43: mlsolid.v1.MlsolidService.CreateModelRegistry:output_type -> mlsolid.v1.CreateModelRegistryResponse
	28, // 44: mlsolid.v1.MlsolidService.ModelRegistry:output_type -> mlsolid.v1.ModelRegistryResponse
	30, // 45: mlsolid.v1.MlsolidService.AddModelEntry:output_type -> mlsolid.v1.AddModelEntryResponse
	32, // 46: mlsolid.v1.MlsolidService.TaggedModel:output_type -> mlsolid.v1.TaggedModelResponse
	34, // 47: mlsolid.v1.MlsolidService.StreamTaggedModel:output_type -> mlsolid.v1.StreamTaggedModelResponse
	36, // 48: mlsolid.v1.MlsolidService.TagModel:output_type -> mlsolid.v1.TagModelResponse
	35, // [35:49] is the sub-list for method output_type
	21, // [21:35] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_mlsolid_v1_mlsolid_proto_init() }
func file_proto_mlsolid_v1_mlsolid_proto_init() {
	if File_proto_mlsolid_v1_mlsolid_proto != nil {
		return
	}
	file_proto_mlsolid_v1_mlsolid_proto_msgTypes[0].OneofWrappers = []any{
		(*Val_Int)(nil),
		(*Val_Double)(nil),
		(*Val_Str)(nil),
	}
	file_proto_mlsolid_v1_mlsolid_proto_msgTypes[20].OneofWrappers = []any{
		(*AddArtifactRequest_Metadata)(nil),
		(*AddArtifactRequest_Content)(nil),
	}
	file_proto_mlsolid_v1_mlsolid_proto_msgTypes[23].OneofWrappers = []any{
		(*ArtifactResponse_Metadata)(nil),
		(*ArtifactResponse_Content)(nil),
	}
	file_proto_mlsolid_v1_mlsolid_proto_msgTypes[33].OneofWrappers = []any{
		(*StreamTaggedModelResponse_Metadata)(nil),
		(*StreamTaggedModelResponse_Content)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mlsolid_v1_mlsolid_proto_rawDesc), len(file_proto_mlsolid_v1_mlsolid_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mlsolid_v1_mlsolid_proto_goTypes,
		DependencyIndexes: file_proto_mlsolid_v1_mlsolid_proto_depIdxs,
		EnumInfos:         file_proto_mlsolid_v1_mlsolid_proto_enumTypes,
		MessageInfos:      file_proto_mlsolid_v1_mlsolid_proto_msgTypes,
	}.Build()
	File_proto_mlsolid_v1_mlsolid_proto = out.File
	file_proto_mlsolid_v1_mlsolid_proto_goTypes = nil
	file_proto_mlsolid_v1_mlsolid_proto_depIdxs = nil
}
